#!/bin/bash

# Integration tests for tic tac toe game

assert_eq() {
  local expected="$1"
  local actual="$2"
  local msg="$3"

  if [ "$expected" == "$actual" ]; then
    return 0
  else
    echo $msg
    return 1
  fi
}

# simple player 1 win game
echo "1 2 3 4 5 6 7" | ./ttt > /dev/null
assert_eq $? 1 "player1 should win"

# simple player 2 win game
echo "1 2 3 5 7 8" | ./ttt > /dev/null
assert_eq $? 2 "player2 should win"
